server:
  port: 8080

spring:
  application:
    name: be-api
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
        # 6. (중요) 'create'나 'update'로 설정
        #    'create': 매번 서버 켤 때마다 테이블 전부 드랍하고 새로 만듦 (데이터 삭제됨)
        #    'update': 엔티티 변경점만 감지해서 DB에 반영 (데이터 유지됨)
      ddl-auto: update



springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /v3/api-docs

app:
  jwt:
    secret: "WlV5b1p3ZjlxQmJvRzZyOXpZK0FteS1wSFh3czZfV2h5Zk1wbUhYd2s5S0pU"
    issuer: my-backend-api
    audience: web
    access-token-validity-ms: 900000
    refresh-token-validity-ms: 1209600000
    clock-skew-sec: 60
  oauth:
    kakao:
      client-id: ${KAKAO_REST_API_KEY}
      redirect-uri: ${KAKAO_REDIRECT_URI}
      client-secret: ""
      admin-key: ""

logging:
  level:
    org.springframework.security: DEBUG
