server:
  port: 8080

spring:
  application:
    name: be-api

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /v3/api-docs

app:
  jwt:
    access-token-validity-ms: 3600000
    refresh-token-validity-ms: 1209600000
    secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa #임시 64bytes random secret. 실제 배포 환경에서는 .env에 설정할 것.
