server:
  port: 8080

spring:
  application:
    name: be-api
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: Asia/Seoul
    hibernate:
        # 6. (중요) 'create'나 'update'로 설정
        #    'create': 매번 서버 켤 때마다 테이블 전부 드랍하고 새로 만듦 (데이터 삭제됨)
        #    'update': 엔티티 변경점만 감지해서 DB에 반영 (데이터 유지됨)
      ddl-auto: update



springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /v3/api-docs

app:
  jwt:
    secret: "WlV5b1p3ZjlxQmJvRzZyOXpZK0FteS1wSFh3czZfV2h5Zk1wbUhYd2s5S0pU"
    issuer: my-backend-api
    audience: web
    access-token-validity-ms: 10800000   # 3 hours
    refresh-token-validity-ms: 1209600000
    clock-skew-sec: 60
  oauth:
    kakao:
      client-id: ${KAKAO_REST_API_KEY}
      redirect-uri: ${KAKAO_REDIRECT_URI}
      client-secret: ""
      admin-key: ""

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

aws:
  access-key: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION}
  s3:
    bucket: sai-final-bucket-asdfasdf

categories:
  - name: "책"
    children:
      - "소설"
      - "에세이"
      - "논픽션"
      - "시·문학"
      - "역사·인문"
      - "과학·기술"
      - "만화·그래픽노블"

  - name: "영화·TV"
    children:
      - "영화"
      - "드라마"
      - "다큐"
      - "애니메이션"
      - "예능·리얼리티"
      - "OTT 오리지널"

  - name: "기타 콘텐츠"
    children:
      - "음악"
      - "유튜브"
      - "팟캐스트"
      - "웹툰·웹소설"
      - "게임"
      - "전시·공연"
      - "SNS·밈"
      - "뉴스·시사"
      - "기타"